


FenixAC_Table = {

	ExplosionsSilentBan = true,

	ExplosionsInvisibleBan = true,

	ExplosionsNodamageScaleBan = true,

	ExplosionsList = {

		{	id = 0, 	name = "Grenade", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 1, 	name = "GrenadeLauncher", 		log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 2, 	name = "PipeBoomb", 			log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 3, 	name = "PipeBoomb", 			log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 4, 	name = "Molotov", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 5, 	name = "TankShell", 			log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 6, 	name = "Hi_Octane", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 7, 	name = "Car", 					log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 8, 	name = "Plance", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 9, 	name = "PetrolPump", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 10 },
		{	id = 10, 	name = "Bike", 					log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 11, 	name = "Dir_Steam", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 12, 	name = "Dir_Flame", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 2 },
		{	id = 13, 	name = "Dir_Water_Hydrant", 	log = true, ban = false , 	cancelevent = true, checkbypass = true, maxexplosion = 6 },
		{	id = 14, 	name = "Dir_Gas_Canister", 		log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 6 },
		{	id = 15, 	name = "Boat", 					log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 16, 	name = "Ship_Destroy", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 17, 	name = "Truck", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 18, 	name = "Bullet", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 19, 	name = "SmokeGrenadeLauncher",	log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 20, 	name = "SmokeGrenade", 			log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 21, 	name = "BZGAS", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 22, 	name = "Flare", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 23, 	name = "Gas_Canister", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 24, 	name = "Extinguisher",			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 25, 	name = "Programmablear", 		log = true, ban = false,	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 26, 	name = "Train", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 27, 	name = "Barrel", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 28, 	name = "PROPANE", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 29, 	name = "Blimp", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 2 },
		{	id = 30, 	name = "Dir_Flame_Explode", 	log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 31, 	name = "Tanker", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 2 },
		{	id = 32, 	name = "PlaneRocket", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 32, 	name = "PlaneRocket", 			log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 34, 	name = "Gas_Tank", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 33, 	name = "VehicleBullet", 		log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 35, 	name = "FireWork", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 36, 	name = "SnowBall", 				log = true, ban = false, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 37, 	name = "ProxMine", 				log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
		{	id = 38, 	name = "Valkyrie_Cannon", 		log = true, ban = true, 	cancelevent = true, checkbypass = true, maxexplosion = 1 },
	},

	AntiSpawnMassEntity = true,

	MaxVehicleSpowned = 10, 

	MaxPedSpowned = 20,
	
	BlacklistedEntityCreating = {
	
	},
	BlacklistedVehicleCreating = {
			--VEHICLES
			"skylift",
			"valkyrie2",
			"airbus",
			"hunter",
			"armytanker",
			"armytrailer",
			"armytrailer2",
			"baletrailer",
			"cablecar",
			"docktrailer",
			"freighttrailer",
			"graintrailer",
			"proptrailer",
			"raketrailer",
			"tr2",
			"tr3",
			"tr4",
			"trflat",
			"hydra",
			"tvtrailer",
			"tanker",
			"tanker2",
			"trailerlarge",
			"trailerlogs",
			"trailersmall",
			"trailers",
			"trailers2",
			"trailers3",
			"trailers4",
			'RHINO',
			'SAVAGE',
			'HUNTER',
			'BUZZARD',
			--'BUZZARD2',
			'ANNIHILATOR',
			'VALKYRIE',
			'APC',
			'Trailersmall2',
			'oppressor',
			'rcbandito',
			'mogul',
			'barrage',
			'Khanjali',
			'volatol',
			'seabreeze',
			'chernobog',
			'avenger',
			'stromberg',
			'zhaba',
			'alkonost',
			'nightshark',
			'babushka ',
			'starling',
			'deluxo',
			'menacer',
			'scramjet',
			'oppressor2',
			'revolter',
			'viseris',
			'savestra',
			'thruster',
			'ardent',
			'ruiner3',
			'dune3',
			'dune2',
			'pbus2',
			'dune5',
			'tampa3',
			'nokota',
			'bombushka',
			'molotok',
			'pyro',
			'ruiner2',
			'limo2',
			'wastelander',
			'jb700w',
			'rallytruck',
			'blazer5',
			'insurgent3',
			'boxville5',
			'bruiser',
			'bruiser2',
			'bruiser3',
			'brutus',
			'brutus2',
			'brutus3',
			'cerberus',
			'cerberus2',
			'cerberus3',
			'dominator4',
			'dominator5',
			'dominator6',
			'impaler2',
			'impaler3',
			'impaler4',
			'imperator',
			'imperator2',
			'imperator3',
			'issi4',
			'issi5',
			'issi6',
			'monster3',
			'monster4',
			'monster5',
			'scarab',
			'scarab2',
			'scarab3',
			'slamvan4',
			'slamvan5',
			'slamvan6',
			'zr380',
			'zr3802',
			'zr3803',
			'alphaz1',
			'avenger2',
			'blimp',
			'blimp2',
			'blimp3',
			'cargoplane',
			'howard',
			'mammatus',
			'microlight',
			'nimbus',
			'rogue',
			'shamal',
			'titan',
			'tula',
			'velum',
			'velum2',
			'vestra',
			'dump',
			--'rumpo',
			'Tipper',
			'DockHandler',
			'Dozer',
			'Dump',
			'Mixer',
			'Rubble',
			'Tipper',
			'benson',
			'benson',
			'cerberus',
			'cerberus2',
			'cerberus3',
			'hauler',
			'hauler2',
			--'mule',
			--'mule2',
			--'mule3',
			--'mule4',
			'packer',
			'phantom',
			'phantom2',
			'phantom3',
			'pounder',
			'pounder2',
	},

	BlacklistedPedsCreating = {
			-- PEDS
			"a_m_m_acult_01",
			"s_m_y_swat_01",
			"a_m_o_acult_01",
			"ig_wade",
			"s_m_y_hwaycop_01",
			"A_M_Y_ACult_01",
			's_m_m_movalien_01',
			's_m_m_movallien_01',
			'u_m_y_babyd',
			'CS_Orleans',
			'A_M_Y_ACult_01',
			'S_M_M_MovSpace_01',
			'U_M_Y_Zombie_01',
			's_m_y_blackops_01',
			'a_f_y_topless_01',
			"s_f_y_bartender_01",
			"a_m_y_beachvesp_01",
			"a_m_y_beach_03",
			"a_m_y_beach_02",
			"a_m_m_beach_02",
			"a_m_y_beach_01",
			"s_m_y_baywatch_01",
			"mp_f_boatstaff_01",
			"u_m_m_bikehire_01", 
			"a_f_y_bevhills_04",
			"s_m_m_bouncer_01",
			"s_m_y_armymech_01", 
			"s_m_y_autopsy_01",
			"s_m_y_blackops_01",
			"s_m_y_blackops_02"
	},

	BlacklistWord = {
		"administrator", "menu", "adm1n", "adm!n", "admln", "moderator", "owner", "nigger", "n1gger", "moderator", "eulencheats", "lynxmenu", "atgmenu", "hacker", "bastard", "hamhaxia", "333gang", "ukrp", "eguk", "n1gger", "n1ga", "nigga", "n1gga", "nigg3r",
    "nig3r", "shagged", "4dm1n", "4dmin", "m0d3r4t0r", "n199er", "n1993r", "rustchance.com", "rustchance", "hellcase.com", "hellcase", "youtube.com", "youtu.be", "youtube", "twitch.tv", "twitch", "anticheat.gg", "anticheat", "fucking", "ψ", "@", "&", "{", "}", ";", "ϟ", "♕", "Æ", "Œ", "‰", "™", "š", "œ", "Ÿ", "µ", "ß",
    "±", "¦", "»", "«", "¼", "½", "¾", "¬", "¿", "Ñ", "®", "©", "²", "·", "•", "°", "þ", "ベ", "ル", "ろ", "ぬ", "ふ", "う", "え", "お", "や", "ゆ", "よ", "わ", "ほ", "へ", "た", "て", "い", "す", "か", "ん", "な", "に", "ら", "ぜ", "む",
    "ち", "と", "し", "は", "き", "く", "ま", "の", "り", "れ", "け", "む", "つ", "さ", "そ", "ひ", "こ", "み", "も", "ね", "る", "め", "ロ", "ヌ", "フ", "ア", "ウ", "エ", "オ", "ヤ", "ユ", "ヨ", "ワ", "ホ", "ヘ", "タ", "テ", "イ", "ス", "カ", "ン",
    "ナ", "ニ", "ラ", "セ", "ム", "チ", "ト", "シ", "ハ", "キ", "ク", "マ", "ノ", "リ", "レ", "ケ", "ム", "ツ", "サ", "ソ", "ヒ", "コ", "ミ", "モ", "ネ", "ル", "メ", "✪", "Ä", "ƒ", "Ã", "¢", "?", "†", "€", "웃", "и", "】", "【", "j4p.pl", "ֆ", "ȶ",
    "你", "好", "爱", "幸", "福", "猫", "狗", "微", "笑", "中", "安", "東", "尼", "杰", "诶", "西", "开", "陈", "瑞", "华", "馬", "塞", "洛", "ダ", "仇", "觉", "感", "衣", "德", "曼", "L͙", "a͙", "l͙", "ľ̶̚͝", "Ḩ̷̤͚̤͑͂̎̎͆", "a̸̢͉̠͎͒͌͐̑̇", "♚", "я", "Ʒ", "Ӂ̴", "Ƹ̴", "≋",
    "API-AC", "civilgamers.com", "civilgamers", "csgoempire.com", "csgoempire", "g4skins.com", "g4skins", "gameodds.gg", "duckfuck.com", "crysishosting.com", "crysishosting", "key-drop.com", "key-drop.pl", "skinhub.com", "skinhub", "`", "¤", "¡",
    "casedrop.eu", "casedrop", "cs.money", "rustypot.com", "ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â", "✈", "⛧", "☭", "☣", "✠", "dkb.xss.ht", "( . )( . )", "⚆", "╮", "╭", "rampage.lt", "?", "xcasecsgo.com", "xcasecsgo", "csgocases.com",
    "csgocases", "K9GrillzUK.co.uk", "moat.gg", "princevidz.com", "princevidz", "pvpro.com", "Pvpro", "ez.krimes.ro", "loot.farm", "arma3fisherslife.net", "arma3fisherslife", "egamers.io", "ifn.gg", "key-drop", "sups.gg", "tradeit.gg",
    "§", "csgotraders.net", "csgotraders", "Σ", "Ξ", "hurtfun.com", "hurtfun", "gamekit.com", "¥", "t.tv", "yandex.ru", "yandex", "csgofly.com", "csgofly", "pornhub.com", "pornhub", "一", "", "Ｊ", "◢", "◤", "⋡", "℟", "ᴮ", "ᴼ", "ᴛᴇᴀᴍ",
    "cs.deals","twat", "STRESS.PW", "<script"
	},
}

